version: '3.9'

services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.8-management-alpine
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  primary_db:
    container_name: primary_db
    image: postgres
    environment:
      - POSTGRES_USER=${PRIMARY_DB_USERNAME}
      - POSTGRES_PASSWORD=${PRIMARY_DB_PASSWORD}
      - POSTGRES_DB=POSTGRES_DB=${PRIMARY_DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - primary_db_data:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
  primary_db_data:
    driver: local

networks:
  backend:
    driver: bridge
