version: '3.9'

services:
  gateway:
    container_name: gateway_service
    build:
      context: .
      target: development
      dockerfile: ./apps/gateway/Dockerfile
    env_file:
      - .env
    ports:
      - '3020:3020'
    networks:
      - backend
    depends_on:
      - member
      - rabbit
  member:
    container_name: member_service
    build:
      context: .
      target: development
      dockerfile: ./apps/member/Dockerfile
    networks:
      - backend
    depends_on:
      - primary_db
      - rabbit
  account:
    container_name: account_service
    build:
      context: .
      target: development
      dockerfile: ./apps/account/Dockerfile
    networks:
      - backend
    depends_on:
      - primary_db
      - rabbit
  story:
    container_name: story_service
    build:
      context: .
      target: development
      dockerfile: ./apps/story/Dockerfile
    networks:
      - backend
    depends_on:
      - primary_db
      - rabbit
  feed:
    container_name: feed_service
    build:
      context: .
      target: development
      dockerfile: ./apps/feed/Dockerfile
    networks:
      - backend
    depends_on:
      - primary_db
      - rabbit
  moderation:
    container_name: moderation_service
    build:
      context: .
      target: development
      dockerfile: ./apps/moderation/Dockerfile
    networks:
      - backend
    depends_on:
      - primary_db
      - rabbit
  survey:
    container_name: survey_service
    build:
      context: .
      target: development
      dockerfile: ./apps/survey/Dockerfile
    networks:
      - backend
    depends_on:
      - primary_db
      - rabbit

networks:
  backend:
    driver: bridge
