version: '3.9'

services:
  gateway:
    container_name: gateway_service
    build:
      context: .
      target: production
      dockerfile: ./apps/gateway/Dockerfile
    env_file:
      - .env
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    depends_on:
      - primary_db
      - rabbit
  rabbitmq3:
    container_name: rabbit
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - ${RABBIT_MQ_PORT}:5672
  primary_db:
    container_name: primary_db
    image: postgres
    environment:
      - POSTGRES_USER=${PRIMARY_DB_USERNAME}
      - POSTGRES_PASSWORD=${PRIMARY_DB_PASSWORD}
      - POSTGRES_DB=${PRIMARY_DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PRIMARY_DB_PORT}:5432
    volumes:
      - primary_db_data:/var/lib/postgresql/data
  db_manager:
    container_name: db_manager
    image: adminer
    ports:
      - ${DB_MANAGER_PORT}:8080

volumes:
  primary_db_data:
    driver: local
