version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@2.0.3

kubectl-job:
  docker:
    - image: cimg/base:stable
  steps:
    - aws-cli/setup
    - checkout
    - run:
        name: apply env to Scripts
        command: |
          circleci env subst < < ./local.env.template > ./envs/local.env
    - aws-ecr/build_and_push_image:
        dockerfile: Dockerfile
        create-repo: true
        context: aws
        repo: ourherd-microservices-backend
        auth:
          - aws-cli/setup:
              role_arn: arn:aws:iam::362275395647:user/development-user

workflows:
  build-and-push-backend-gateway:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: backend-gateway