version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@4.0

jobs: 
  build-push-image-service:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-cli/setup
      - checkout
      - run:
          name: apply env to Scripts
          command: |
            circleci env subst < ./local.env.template > ./envs/local.env
      - aws-ecr/build_and_push_image:
          dockerfile: Dockerfile
          create_repo: true
          repo: ourherd-microservices-backend
          region: ap-southeast-2
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::362275395647

workflows:
  build-and-push-backend-gateway:
    jobs:
      - build-push-image-service:
          context: aws