version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.1
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@4.0
  docker: circleci/docker@2.4.0

jobs: 
  build-push-image-service:
    docker:
      - image: cimg/base:stable
    steps:
      - aws-cli/setup
      - checkout
      - docker/install-docker
      - run:
          name: create file & folder
          command: |
            mkdir envs && touch ./envs/local.env
      - run:
          name: apply env to Scripts
          command: |
            circleci env subst < ./local.env.template > ./envs/local.env
      - run:
          name: erc login
          command: |
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 362275395647.dkr.ecr.ap-southeast-2.amazonaws.com
      - run:
          name: docker build
          command: |
            docker build -t ourherd-microservices-backend .
      - run:
          name: docker tag
          command: |
            docker tag ourherd-microservices-backend:latest 362275395647.dkr.ecr.ap-southeast-2.amazonaws.com/ourherd-microservices-backend:latest
      - run:
          name: docker push
          command: |
            docker push 362275395647.dkr.ecr.ap-southeast-2.amazonaws.com/ourherd-microservices-backend:latest
      # - aws-ecr/build_and_push_image:
      #     dockerfile: Dockerfile
      #     create_repo: true
      #     repo: ourherd-microservices-backend
      #     auth:
      #       - aws-cli/setup

workflows:
  build-and-push-backend-gateway:
    jobs:
      - build-push-image-service:
          context: aws