export enum RabbitServiceName {
    MEMBER = "MEMBER_SERVICE",
    FEED = "FEED_SERVICE",
    STORY = "STORY_SERVICE",
    ACCOUNT = "ACCOUNT_SERVICE",
    SURVEY = "SURVEY_SERVICE",
    MODERATION = "MODERATION_SERVICE",
    EMAIL = "EMAIL_SERVICE",
    NOTIFICATION = "NOTIFICATION_SERVICE",
    STORAGE = "STORAGE_SERVICE",
}
